# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error1_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(290, 117)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        Form.setFont(font)
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(100, 20, 181, 36))
        self.label1.setScaledContents(False)
        self.label1.setWordWrap(False)
        self.label1.setObjectName("label1")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(100, 80, 93, 28))
        self.pushButton1.setObjectName("pushButton1")
        
        self.pushButton1.clicked.connect(QtCore.QCoreApplication.instance.quit)
        
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(11, 11, 61, 61))
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap("cancel.png"))
        self.label2.setScaledContents(True)
        self.label2.setObjectName("label2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Error"))
        self.label1.setText(_translate("Form", "You cant select more than one <br>wicket-keeper"))
        self.pushButton1.setText(_translate("Form", "OK"))        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
